# Generated by Django 6.0.2 on 2026-02-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='unidad_pago',
            field=models.CharField(choices=[('HORA', 'Hora'), ('DIA', 'Día'), ('SEMANA', 'Semana'), ('MES', 'Mes'), ('SERVICIO', 'Servicio'), ('M2', 'm²'), ('ML', 'Metro lineal'), ('VIAJE', 'Viaje'), ('UNIDAD', 'Unidad')], default='DIA', max_length=20),
        ),
    ]
